### ISSUE TITLE
No License file

### ISSUE THREAD

**Issue by dardevelin** [EUCouncil/CouncilVotesOnActsDatasetSample#1]
Hello, id like to mention that this project contains no license file
nor does have mention of a preferred license, preventing people from
contributing as well as safe usage of the software as the current form maintain
it as 'copyrighted to the original author'.

I would therefor recommend EUPL (since it is from EUcouncil)

Thanks in advance

**Comment by 2mac** [comment]
I agree. In many jurisdictions, this software would not respect the freedoms of its users since the assumed license is "All Rights Reserved."

**Comment by simonech** [comment]
I agree, the repo was put up in a rush to show it at the webinar for diploack and I forgot to add the license file, which will indeed be the EUPL.
I'll update the readme file and upload the license file asap.
Thx for reporting the issue
